### ISSUE TITLE
[contract, server] Store person's name, remove account number

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-poba#57]
As per [this comment](https://github.com/poanetwork/poa-poba/issues/43#issuecomment-393207564) we don't need to store bank account number.

However, I think we should also add person's name from https://plaid.com/docs/api/#identity otherwise it's possible to ask another person to login into plaid and provide incorrect account information.

**Comment by matiasgaratortiz** [comment]
@phahulin About what we were talking about before, since we need to identify the accounts, we would have to save the bank account number or the Plaid id of each account. On the other hand, if you register 2 or more accounts of a bank, and list the accounts already registered, how do you know which ones you have already registered and which ones do not? We also need to show the name of the bank, because it could be several accounts of several banks. That was the idea of storing the bank account number. what do you think about?

**Comment by unjapones** [comment]
@phaulin , @igorbarinov I have a couple of questions regarding this issue:

#### 1. Regarding the person's name
I started by adding the person's name to the data stored in the contract (retrieved via Plaid's `/identity` endpoint).

I believe _we don't need to show or do anything on the DApp's UI in this regard, right?_ Just wanted to confirm this.

#### 2. Regarding the removal of the account number
What Matias pointed out in the previous comment makes sense to me, unless we want to attest:
> _the fact that a given person has an account **of any type[1]** on a given bank_. 

If this is the requirement, I would like to handle it in a different issue.

Notes:
* [1] Plaid specifies multiple account types (section "Account Type") in https://plaid.com/docs/#accounts.

cc @pablofullana

**Comment by phahulin** [comment]
1. Right
2. The thing with bank accounts is that they are private data, so we shouldn't be storing them publicly. I'm not sure if we can find another "id", that would differentiate user's accounts, and at the same time be useful for verification. This is why I suggest we stick to one account per bank. What's your opinion on that? Maybe I'm missing some possibility here.
Thanks

**Comment by unjapones** [comment]
Regarding the bank account number:

* It looks like there is no other information provided by Plaid to identify an individual bank account, given an institution. Plaid generates and API ID, but I don't think we should store it in the contract.
* I don't think the bank account number is confidential information like a password. You can keep it _private_ to some extent by choosing who to share it with, but it may not remain confidential (for example, when you emit a check, these numbers appear at the bottom of it and they become visible for everyone that handles the check). 
* Unfortunately I don't know how the legislation (US/other) regulates the storage & publication of this kind data.

Note that if we change the DApp to only atestate that a person has an account on a given bank, we may have to simplify the UI. For example, the lists with bank accounts items may dissapear, right?

@igorbarinov what's your opinion on this regard?

**Comment by unjapones** [comment]
@igorbarinov as we discussed this on las Friday's the demo:

> The UI will show the name (what Plaid's Identity endpoint/service provides) instead of the bank account number.

Considering @phahulin 's comment above, we will probably stick to one verified account per bank, since there will not be a way to differentiate to _verified bank accounts_, unless we store the account number hashed or something like that.
